### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hita03** [Tech-Matrix/WatchNext--Sentiment-analysis-based-recommendation-system#2]
**Is your feature request related to a problem? Please describe.**
It's preferable to be able to visually see dataframes and outcomes.
It helps gain insight on the data, to recognize patterns.

**Describe the solution you'd like**
To include data plots/pie charts of the recommended movies vs their ratings to the user, and other plots wherever appropriate. 

 I would like to be assigned to this issue.

**Comment by charvibannur** [comment]
Seems neat! I've assigned it.
